[package]
name = "blog-api"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-cors = "0.6.5"
actix-web = "4.5.1"
futures-util = "0.3.30"
log = "0.4.21"
r2d2 = "0.8.10"
r2d2_sqlite = "0.23.0"
rusqlite = "0.30.0"
serde = "1.0.196"
serde_derive = "1.0.196"
